"""hw5

Revision ID: 6109a31e7212
Revises: 
Create Date: 2021-10-18 08:19:20.796178

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6109a31e7212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chats',
        sa.Column('chat_id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('chat_name', sa.String(length=255), nullable=False),
        sa.CheckConstraint('char_length(chat_name) > 0', name=op.f('ck__chats__chat_name_min_len_check')),
        sa.PrimaryKeyConstraint('chat_id', name=op.f('pk__chats')))

    op.create_table(
        'global_users',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('login', sa.String(length=255), nullable=False),
        sa.Column('password_hash_sha512', sa.String(length=128), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('utc_offset', sa.SmallInteger(), nullable=False),
        sa.CheckConstraint('char_length(login) > 0', name=op.f('ck__global_users__login_min_len_check')),
        sa.CheckConstraint('char_length(name) > 0', name=op.f('ck__global_users__name_min_len_check')),
        sa.CheckConstraint('char_length(password_hash_sha512) = 128',
                           name=op.f('ck__global_users__password_hash_sha512_len_check')),
        sa.CheckConstraint('utc_offset >= -24 and utc_offset <= 24', name=op.f('ck__global_users__utc_offset_check')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__global_users')))

    op.create_index(op.f('ix__global_users__login'), 'global_users', ['login'], unique=True)

    op.create_table(
        'chats_users',
        sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_name', sa.String(length=255), nullable=False),
        sa.Column('chat_id', sa.BigInteger(), nullable=False),
        sa.Column('global_user_id', sa.BigInteger(), nullable=False),
        sa.CheckConstraint('char_length(user_name) > 0', name=op.f('ck__chats_users__user_name_min_len_check')),
        sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk__chats_users__chat_id__chats')),
        sa.ForeignKeyConstraint(['global_user_id'], ['global_users.id'],
                                name=op.f('fk__chats_users__global_user_id__global_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', name=op.f('pk__chats_users')))

    op.create_index(op.f('ix__chats_users__chat_id'), 'chats_users', ['chat_id'], unique=False)
    op.create_index(op.f('ix__chats_users__global_user_id'), 'chats_users', ['global_user_id'], unique=False)

    op.create_table(
        'users_sessions',
        sa.Column('session_id', sa.String(length=128), nullable=False),
        sa.Column('global_user_id', sa.BigInteger(), nullable=False),
        sa.CheckConstraint('char_length(session_id) = 128', name=op.f('ck__users_sessions__session_id_len_check')),
        sa.ForeignKeyConstraint(['global_user_id'], ['global_users.id'],
                                name=op.f('fk__users_sessions__global_user_id__global_users')),
        sa.PrimaryKeyConstraint('session_id', name=op.f('pk__users_sessions')))

    op.create_index(op.f('ix__users_sessions__global_user_id'), 'users_sessions', ['global_user_id'], unique=False)

    op.create_table(
        'chats_messages',
        sa.Column('message_id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('msg', sa.Text(), nullable=False),
        sa.Column('chat_id', sa.BigInteger(), nullable=False),
        sa.Column('from_chat_user', sa.BigInteger(), nullable=False),
        sa.CheckConstraint('char_length(msg) > 0', name=op.f('ck__chats_messages__msg_min_len_check')),
        sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk__chats_messages__chat_id__chats'),
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['from_chat_user'], ['chats_users.user_id'],
                                name=op.f('fk__chats_messages__from_chat_user__chats_users')),
        sa.PrimaryKeyConstraint('message_id', name=op.f('pk__chats_messages')))

    op.create_index(op.f('ix__chats_messages__chat_id'), 'chats_messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__chats_messages__chat_id'), table_name='chats_messages')
    op.drop_table('chats_messages')
    op.drop_index(op.f('ix__users_sessions__global_user_id'), table_name='users_sessions')
    op.drop_table('users_sessions')
    op.drop_index(op.f('ix__chats_users__global_user_id'), table_name='chats_users')
    op.drop_index(op.f('ix__chats_users__chat_id'), table_name='chats_users')
    op.drop_table('chats_users')
    op.drop_index(op.f('ix__global_users__login'), table_name='global_users')
    op.drop_table('global_users')
    op.drop_table('chats')
    # ### end Alembic commands ###
